// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartFxJournal.JournalDB.model;

#nullable disable

namespace SmartFxJournal.JournalDB.migrations
{
    [DbContext(typeof(JournalDbContext))]
    [Migration("20230609134921_AlterClosedPosition")]
    partial class AlterClosedPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.CTraderAccount", b =>
                {
                    b.Property<string>("CTraderId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("c_trader_id");

                    b.Property<string>("AccessToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("access_token");

                    b.Property<string>("AuthToken")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("auth_token");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_secret");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("ExpiresOn")
                        .HasColumnType("bigint")
                        .HasColumnName("expires_on");

                    b.Property<long?>("LastFetchedOn")
                        .HasColumnType("bigint")
                        .HasColumnName("last_fetched_on");

                    b.Property<DateTime>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_on")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("refresh_token");

                    b.HasKey("CTraderId")
                        .HasName("pk_ctradermaster");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_ctradermaster_client_id");

                    b.ToTable("ctradermaster", (string)null);
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.ClosedPosition", b =>
                {
                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<long>("AccountNo")
                        .HasColumnType("bigint")
                        .HasColumnName("account_no");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("balance_after");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("commission");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("entry_price");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("exit_price");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gross_profit");

                    b.Property<bool>("IsMultiOrderPosition")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_order_position");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<decimal>("NetProfit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("net_profit");

                    b.Property<DateTimeOffset>("OrderClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_closed_at");

                    b.Property<DateTimeOffset>("OrderOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_opened_at");

                    b.Property<short>("PositionStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("position_status");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("stop_loss");

                    b.Property<decimal>("Swap")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("swap");

                    b.Property<short>("Symbol")
                        .HasColumnType("smallint")
                        .HasColumnName("symbol");

                    b.Property<decimal?>("TakeProfit")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("take_profit");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("PositionId")
                        .HasName("pk_tradedpositions");

                    b.HasIndex("AccountNo")
                        .HasDatabaseName("ix_tradedpositions_account_no");

                    b.ToTable("tradedpositions", (string)null);
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.ExecutedOrder", b =>
                {
                    b.Property<long>("DealId")
                        .HasColumnType("bigint")
                        .HasColumnName("deal_id");

                    b.Property<long>("AccountNo")
                        .HasColumnType("bigint")
                        .HasColumnName("account_no");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("balance_after");

                    b.Property<long>("ClosedVolume")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_volume");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("commission");

                    b.Property<short>("DealStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("deal_status");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<decimal>("ExecutionPrice")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("execution_price");

                    b.Property<long>("FilledVolume")
                        .HasColumnType("bigint")
                        .HasColumnName("filled_volume");

                    b.Property<decimal>("GrossProfit")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gross_profit");

                    b.Property<bool>("IsClosing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closing");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<DateTimeOffset>("OrderExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_executed_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("position_id");

                    b.Property<decimal>("Swap")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("swap");

                    b.Property<short>("Symbol")
                        .HasColumnType("smallint")
                        .HasColumnName("symbol");

                    b.HasKey("DealId")
                        .HasName("pk_executedorders");

                    b.HasIndex("AccountNo")
                        .HasDatabaseName("ix_executedorders_account_no");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_executedorders_position_id");

                    b.ToTable("executedorders", (string)null);
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.TradingAccount", b =>
                {
                    b.Property<long>("AccountNo")
                        .HasColumnType("bigint")
                        .HasColumnName("account_no");

                    b.Property<string>("AccountCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(10)")
                        .HasColumnName("account_currency")
                        .HasDefaultValueSql("'EUR'::character varying");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("broker");

                    b.Property<long?>("CTraderAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("c_trader_account_id");

                    b.Property<string>("CTraderId")
                        .HasColumnType("character varying(256)")
                        .HasColumnName("c_trader_id");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("current_balance");

                    b.Property<short>("ImportMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("import_mode")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_live");

                    b.Property<long>("LastImportedOn")
                        .HasColumnType("bigint")
                        .HasColumnName("last_imported_on");

                    b.Property<DateTime>("LastModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_on")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("OpenedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("opened_on")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("StartBalance")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("start_balance");

                    b.HasKey("AccountNo")
                        .HasName("pk_tradingaccounts");

                    b.HasIndex("CTraderId")
                        .HasDatabaseName("ix_tradingaccounts_c_trader_id");

                    b.ToTable("tradingaccounts", null, t =>
                        {
                            t.HasCheckConstraint("chk_positive", "account_no > 0");
                        });
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.ClosedPosition", b =>
                {
                    b.HasOne("SmartFxJournal.JournalDB.model.TradingAccount", "TradingAccount")
                        .WithMany("Positions")
                        .HasForeignKey("AccountNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tradedpositions_tradingaccounts_trading_account_account_no");

                    b.Navigation("TradingAccount");
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.ExecutedOrder", b =>
                {
                    b.HasOne("SmartFxJournal.JournalDB.model.TradingAccount", "TradingAccount")
                        .WithMany("ExecutedOrders")
                        .HasForeignKey("AccountNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_executedorders_tradingaccounts_trading_account_account_no");

                    b.HasOne("SmartFxJournal.JournalDB.model.ClosedPosition", "Position")
                        .WithMany("ExecutedOrders")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_executedorders_tradedpositions_position_id");

                    b.Navigation("Position");

                    b.Navigation("TradingAccount");
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.TradingAccount", b =>
                {
                    b.HasOne("SmartFxJournal.JournalDB.model.CTraderAccount", "CTraderAccount")
                        .WithMany("TradingAccounts")
                        .HasForeignKey("CTraderId")
                        .HasConstraintName("fk_tradingaccounts_ctradermaster_c_trader_account_c_trader_id");

                    b.Navigation("CTraderAccount");
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.CTraderAccount", b =>
                {
                    b.Navigation("TradingAccounts");
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.ClosedPosition", b =>
                {
                    b.Navigation("ExecutedOrders");
                });

            modelBuilder.Entity("SmartFxJournal.JournalDB.model.TradingAccount", b =>
                {
                    b.Navigation("ExecutedOrders");

                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
